name: Create Image Tag Alias
on:
  workflow_dispatch:
    inputs:
      tag_src:
        description: Old tag
        required: true
      tag_dst:
        description: New tag
        required: true
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository_owner }}/sm-eda-bundle
jobs:
  promote:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Tag Alias
        run: |
          docker buildx imagetools create \
            -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.event.inputs.tag_dst }} \
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.event.inputs.tag_src }}
      - name: Inspect New Tag
        run: |
          docker buildx imagetools inspect ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.event.inputs.tag_dst }}
